common: &common
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *common

test:
  <<: *common
  #database: websocket_chat_test

production:
  <<: *common
  #database: websocket_chat
